// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhzfGFSggXLcCow2qLXwEc2Cdm0PEfKzE',
    appId: '1:675068008648:web:64e2ef64a1a9d620872dfd',
    messagingSenderId: '675068008648',
    projectId: 'quizz-game-629c0',
    authDomain: 'quizz-game-629c0.firebaseapp.com',
    storageBucket: 'quizz-game-629c0.appspot.com',
    measurementId: 'G-YH6B0D1TDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUywK752Xyd1eUSAxJur3J19GKnfpdN24',
    appId: '1:675068008648:android:74872c411d0bc44e872dfd',
    messagingSenderId: '675068008648',
    projectId: 'quizz-game-629c0',
    storageBucket: 'quizz-game-629c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTzzrqQRzLCxkLNwUWIiNFE9g-kZ0Kn4',
    appId: '1:675068008648:ios:5b79f872cb1d715b872dfd',
    messagingSenderId: '675068008648',
    projectId: 'quizz-game-629c0',
    storageBucket: 'quizz-game-629c0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASTzzrqQRzLCxkLNwUWIiNFE9g-kZ0Kn4',
    appId: '1:675068008648:ios:66e5415a01169a19872dfd',
    messagingSenderId: '675068008648',
    projectId: 'quizz-game-629c0',
    storageBucket: 'quizz-game-629c0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
