// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-OFBUjNClkm7ET6oDD0eKgO05fA2fl8',
    appId: '1:166904127927:web:48ed588159ed0267b38832',
    messagingSenderId: '166904127927',
    projectId: 'quizz-game-b07ee',
    authDomain: 'quizz-game-b07ee.firebaseapp.com',
    storageBucket: 'quizz-game-b07ee.appspot.com',
    measurementId: 'G-EG26F8R8ZF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_aI9sdgprkLPZNcmCHJgAImovBGUw9ns',
    appId: '1:166904127927:ios:d68c1bef1e07748ab38832',
    messagingSenderId: '166904127927',
    projectId: 'quizz-game-b07ee',
    storageBucket: 'quizz-game-b07ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_aI9sdgprkLPZNcmCHJgAImovBGUw9ns',
    appId: '1:166904127927:ios:de2dcf97868f4de2b38832',
    messagingSenderId: '166904127927',
    projectId: 'quizz-game-b07ee',
    storageBucket: 'quizz-game-b07ee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
